### ISSUE TITLE
file name change

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/brat_to_cdli_conll_converter#4]
I ran this :
```
epp@waga-masta:/alty/data/brat2cdliconll$ brat2conll -v
Input path: train-sample.ann
Info: Processing train-sample.ann.
Info: Reading file train-sample.ann.
epp@waga-masta:/alty/data/brat2cdliconll$ 
```
and the file in output is called ann.conll. Can you have the file named as per the text number?

I think for more extensive testing we will need to wait and get the cdli-conll to conll-u format and the conll-u to brat converters in better shape

**Comment by greek-geek** [comment]
I have fixed the output filename issue. Currently, the output file name is the same as that of the input file with a different file extension. Yes, I can name the output file as per the text number but I am not sure where to find the text number in the input file.

**Comment by epageperron** [comment]
Yes right ! Let's use the .ann file name for the output and until this tool is in the pipeline we'll just export .ann files from Brat with the text number as the file number.

**Comment by greek-geek** [comment]
Okay!

**Comment by jayanthkmr** [comment]
@epageperron What needs to be done here?
